######################################
# Book settings
title: EDA Produto Interno
author: EloGroup
logo: 'elo_logonovo.png'

# Information about where the book exists on the web
description: >-
  Documentação produzida pelo time de Analytics da EloGroup.

######################################
# Execution settings
execute:
  execute_notebooks: cache

######################################
# HTML-specific settings
html:
  home_page_in_navbar: false

######################################
# Interact link settings
notebook_interface: "notebook"

latex:
  latex_engine: "xelatex"
  latex_documents:
    targetname: book.tex
